def return_json(self):
        data = [{'beam': 1 ,'type': 'H','length_direction':'x','width_direction':'y','height_direction':'z','length':length_bim.length,
     'data1': {'p':'1',
                'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2], 
                'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
                'center':[0,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
                'width':length_bim.width,'height':length_bim.flange_thickness},
     'data2': {'p':'1',
               'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.height)/2],
               'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.height)/2],
               'center': [0,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.height)/2],
               'width':length_bim.web_thickness,'height':length_bim.height-2*length_bim.flange_thickness},
     'data3': {'p':'1', 
               'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+2*length_bim.height-length_bim.flange_thickness)/2],
               'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+2*length_bim.height-length_bim.flange_thickness)/2],
               'center': [0,(width_bim.length+length_bim.width)/2,-(height_bim.length+2*length_bim.height-length_bim.flange_thickness)/2],
               'width':length_bim.width,'height':length_bim.flange_thickness}
     },
     {'beam': 2 ,'type': 'H','length_direction':'y','width_direction':'x','height_direction':'z','length':width_bim.length,
     'data1': {'p':'2',
                'center1': [(length_bim.length+width_bim.width)/2,width_bim.length/2,-(height_bim.length+width_bim.flange_thickness)/2], 
                'center2': [(length_bim.length+width_bim.width)/2,-width_bim.length/2,-(height_bim.length+width_bim.flange_thickness)/2],
                'center':[(length_bim.length+width_bim.width)/2,0,-(height_bim.length+width_bim.flange_thickness)/2],
                'width':width_bim.width,'height':width_bim.flange_thickness},
     'data2': {'p':'2',
               'center1': [(length_bim.length+width_bim.width)/2,width_bim.length/2,-(height_bim.length+width_bim.height)/2],
               'center2': [(length_bim.length+width_bim.width)/2,-width_bim.length/2,-(height_bim.length+width_bim.height)/2],
               'center': [(length_bim.length+width_bim.width)/2,0,-(height_bim.length+width_bim.height)/2],
               'width':width_bim.web_thickness,'height':width_bim.height-2*width_bim.flange_thickness},
     'data3': {'p':'2',
                'center1': [(length_bim.length+width_bim.width)/2,width_bim.length/2,-(height_bim.length+2*width_bim.height-width_bim.flange_thickness)/2], 
                'center2': [(length_bim.length+width_bim.width)/2,-width_bim.length/2,-(height_bim.length+2*width_bim.height-width_bim.flange_thickness)/2],
                'center':[(length_bim.length+width_bim.width)/2,0,-(height_bim.length+2*width_bim.height-width_bim.flange_thickness)/2],
                'width':width_bim.width,'height':width_bim.flange_thickness}
     },
     {'beam': 3,'type': 'H','length_direction':'x','width_direction':'y','height_direction':'z','length':length_bim.length,
     'data1': {'p':'3',
                'center1': [-length_bim.length/2,-(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2], 
                'center2': [length_bim.length/2,-(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
                'center':[0,-(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
                'width':length_bim.width,'height':length_bim.flange_thickness},
     'data2': {'p':'3',
               'center1': [-length_bim.length/2,-(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.height)/2],
               'center2': [length_bim.length/2,-(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.height)/2],
               'center': [0,-(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.height)/2],
               'width':length_bim.web_thickness,'height':length_bim.height-2*length_bim.flange_thickness},
     'data3': {'p':'3', 
               'center1': [-length_bim.length/2,-(width_bim.length+length_bim.width)/2,-(height_bim.length+2*length_bim.height-length_bim.flange_thickness)/2],
               'center2': [length_bim.length/2,-(width_bim.length+length_bim.width)/2,-(height_bim.length+2*length_bim.height-length_bim.flange_thickness)/2],
               'center': [0,-(width_bim.length+length_bim.width)/2,-(height_bim.length+2*length_bim.height-length_bim.flange_thickness)/2],
               'width':length_bim.width,'height':length_bim.flange_thickness}
     }, {'beam': 4 ,'type': 'H','length_direction':'y','width_direction':'x','height_direction':'z','length':width_bim.length,
     'data1': {'p':'4',
                'center1': [-(length_bim.length+width_bim.width)/2,width_bim.length/2,-(height_bim.length+width_bim.flange_thickness)/2], 
                'center2': [-(length_bim.length+width_bim.width)/2,-width_bim.length/2,-(height_bim.length+width_bim.flange_thickness)/2],
                'center':[-(length_bim.length+width_bim.width)/2,0,-(height_bim.length+width_bim.flange_thickness)/2],
                'width':width_bim.width,'height':width_bim.flange_thickness},
     'data2': {'p':'4',
               'center1': [-(length_bim.length+width_bim.width)/2,width_bim.length/2,-(height_bim.length+width_bim.height)/2],
               'center2': [-(length_bim.length+width_bim.width)/2,-width_bim.length/2,-(height_bim.length+width_bim.height)/2],
               'center': [-(length_bim.length+width_bim.width)/2,0,-(height_bim.length+width_bim.height)/2],
               'width':width_bim.web_thickness,'height':width_bim.height-2*width_bim.flange_thickness},
     'data3': {'p':'4',
                'center1': [-(length_bim.length+width_bim.width)/2,width_bim.length/2,-(height_bim.length+2*width_bim.height-width_bim.flange_thickness)/2], 
                'center2': [-(length_bim.length+width_bim.width)/2,-width_bim.length/2,-(height_bim.length+2*width_bim.height-width_bim.flange_thickness)/2],
                'center':[-(length_bim.length+width_bim.width)/2,0,-(height_bim.length+2*width_bim.height-width_bim.flange_thickness)/2],
                'width':width_bim.width,'height':width_bim.flange_thickness}
     },{'beam': 5 ,'type': 'H','length_direction':'z','width_direction':'x','height_direction':'y','length':height_bim.length,
     'data1': {'p':'5',
                'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2], 
                'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
                #5~8只改中心
                'center': [(length_bim.length+height_bim.width)/2,(width_bim.length+height_bim.flange_thickness)/2,0],
                'width':height_bim.width,'height':height_bim.flange_thickness},
     'data2': {'p':'5',
               'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.height)/2],
               'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
               'center': [(length_bim.length+height_bim.width)/2,(width_bim.length+height_bim.height)/2,0],
               'width':height_bim.web_thickness,'height':height_bim.height-2*height_bim.flange_thickness},
     'data3': {'p':'5', 
               'center1': [-length_bim.length/2,(width_bim.length+height_bim.flange_thickness)/2,-(height_bim.length-length_bim.height)/2+length_bim.height],
               'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
               'center': [(length_bim.length+height_bim.width)/2,(width_bim.length+2*height_bim.height-height_bim.flange_thickness)/2,0],
               'width':height_bim.width,'height':height_bim.flange_thickness}
     },{'beam': 6 ,'type': 'H','length_direction':'z','width_direction':'x','height_direction':'y','length':height_bim.length,
     'data1': {'p':'6',
                'center1': [-length_bim.length/2,-(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2], 
                'center2': [length_bim.length/2,-(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
                #5~8只改中心
                'center': [(length_bim.length+height_bim.width)/2,-(width_bim.length+height_bim.flange_thickness)/2,0],
                'width':height_bim.width,'height':height_bim.flange_thickness},
     'data2': {'p':'6',
               'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.height)/2],
               'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
               'center': [(length_bim.length+height_bim.width)/2,-(width_bim.length+height_bim.height)/2,0],
               'width':height_bim.web_thickness,'height':height_bim.height-2*height_bim.flange_thickness},
     'data3': {'p':'6', 
               'center1': [-length_bim.length/2,(width_bim.length+height_bim.flange_thickness)/2,-(height_bim.length-length_bim.height)/2+length_bim.height],
               'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
               'center': [(length_bim.length+height_bim.width)/2,-(width_bim.length+2*height_bim.height-height_bim.flange_thickness)/2,0],
               'width':height_bim.width,'height':height_bim.flange_thickness}
     },{'beam': 7 ,'type': 'H','length_direction':'z','width_direction':'x','height_direction':'y','length':height_bim.length,
     'data1': {'p':'7',
                'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2], 
                'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
                #5~8只改中心
                'center': [-(length_bim.length+height_bim.width)/2,(width_bim.length+height_bim.flange_thickness)/2,0],
                'width':height_bim.width,'height':height_bim.flange_thickness},
     'data2': {'p':'7',
               'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.height)/2],
               'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
               'center': [-(length_bim.length+height_bim.width)/2,(width_bim.length+height_bim.height)/2,0],
               'width':height_bim.web_thickness,'height':height_bim.height-2*height_bim.flange_thickness},
     'data3': {'p':'7', 
               'center1': [-length_bim.length/2,(width_bim.length+height_bim.flange_thickness)/2,-(height_bim.length-length_bim.height)/2+length_bim.height],
               'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
               'center': [-(length_bim.length+height_bim.width)/2,(width_bim.length+2*height_bim.height-height_bim.flange_thickness)/2,0],
               'width':height_bim.width,'height':height_bim.flange_thickness}
     },{'beam': 8 ,'type': 'H','length_direction':'z','width_direction':'x','height_direction':'y','length':height_bim.length,
     'data1': {'p':'8',
                'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2], 
                'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
                #5~8只改中心
                'center': [-(length_bim.length+height_bim.width)/2,(width_bim.length+height_bim.flange_thickness)/2,0],
                'width':height_bim.width,'height':height_bim.flange_thickness},
     'data2': {'p':'8',
               'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.height)/2],
               'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
               'center': [-(length_bim.length+height_bim.width)/2,(width_bim.length+height_bim.height)/2,0],
               'width':height_bim.web_thickness,'height':height_bim.height-2*height_bim.flange_thickness},
     'data3': {'p':'8', 
               'center1': [-length_bim.length/2,(width_bim.length+height_bim.flange_thickness)/2,-(height_bim.length-length_bim.height)/2+length_bim.height],
               'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,-(height_bim.length+length_bim.flange_thickness)/2],
               'center': [-(length_bim.length+height_bim.width)/2,(width_bim.length+2*height_bim.height-height_bim.flange_thickness)/2,0],
               'width':height_bim.width,'height':height_bim.flange_thickness}
     },{'beam': 9 ,'type': 'H','length_direction':'x','width_direction':'y','height_direction':'z','length':length_bim.length,
     'data1': {'p':'9',
                'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,(height_bim.length+length_bim.flange_thickness)/2], 
                'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,(height_bim.length+length_bim.flange_thickness)/2],
                'center':[0,(width_bim.length+length_bim.width)/2,(height_bim.length+length_bim.flange_thickness)/2],
                'width':length_bim.width,'height':length_bim.flange_thickness},
     'data2': {'p':'9',
               'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,(height_bim.length+length_bim.height)/2],
               'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,(height_bim.length+length_bim.height)/2],
               'center': [0,(width_bim.length+length_bim.width)/2,(height_bim.length+length_bim.height)/2],
               'width':length_bim.web_thickness,'height':length_bim.height-2*length_bim.flange_thickness},
     'data3': {'p':'9', 
               'center1': [-length_bim.length/2,(width_bim.length+length_bim.width)/2,(height_bim.length+2*length_bim.height-length_bim.flange_thickness)/2],
               'center2': [length_bim.length/2,(width_bim.length+length_bim.width)/2,(height_bim.length+2*length_bim.height-length_bim.flange_thickness)/2],
               'center': [0,(width_bim.length+length_bim.width)/2,(height_bim.length+2*length_bim.height-length_bim.flange_thickness)/2],
               'width':length_bim.width,'height':length_bim.flange_thickness}
     }, {'beam': 10 ,'type': 'H','length_direction':'y','width_direction':'x','height_direction':'z','length':width_bim.length,
     'data1': {'p':'10',
                'center1': [(length_bim.length+width_bim.width)/2,width_bim.length/2,(height_bim.length+width_bim.flange_thickness)/2], 
                'center2': [(length_bim.length+width_bim.width)/2,-width_bim.length/2,(height_bim.length+width_bim.flange_thickness)/2],
                'center':[(length_bim.length+width_bim.width)/2,0,(height_bim.length+width_bim.flange_thickness)/2],
                'width':width_bim.width,'height':width_bim.flange_thickness},
     'data2': {'p':'10',
               'center1': [(length_bim.length+width_bim.width)/2,width_bim.length/2,(height_bim.length+width_bim.height)/2],
               'center2': [(length_bim.length+width_bim.width)/2,-width_bim.length/2,(height_bim.length+width_bim.height)/2],
               'center': [(length_bim.length+width_bim.width)/2,0,(height_bim.length+width_bim.height)/2],
               'width':width_bim.web_thickness,'height':width_bim.height-2*width_bim.flange_thickness},
     'data3': {'p':'10',
                'center1': [(length_bim.length+width_bim.width)/2,width_bim.length/2,(height_bim.length+2*width_bim.height-width_bim.flange_thickness)/2], 
                'center2': [(length_bim.length+width_bim.width)/2,-width_bim.length/2,(height_bim.length+2*width_bim.height-width_bim.flange_thickness)/2],
                'center':[(length_bim.length+width_bim.width)/2,0,(height_bim.length+2*width_bim.height-width_bim.flange_thickness)/2],
                'width':width_bim.width,'height':width_bim.flange_thickness}
     },{'beam': 11 ,'type': 'H','length_direction':'x','width_direction':'y','height_direction':'z','length':length_bim.length,
     'data1': {'p':'11',
                'center1': [-length_bim.length/2,-(width_bim.length+length_bim.width)/2,(height_bim.length+length_bim.flange_thickness)/2], 
                'center2': [length_bim.length/2,-(width_bim.length+length_bim.width)/2,(height_bim.length+length_bim.flange_thickness)/2],
                'center':[0,-(width_bim.length+length_bim.width)/2,(height_bim.length+length_bim.flange_thickness)/2],
                'width':length_bim.width,'height':length_bim.flange_thickness},
     'data2': {'p':'11',
               'center1': [-length_bim.length/2,-(width_bim.length+length_bim.width)/2,(height_bim.length+length_bim.height)/2],
               'center2': [length_bim.length/2,-(width_bim.length+length_bim.width)/2,(height_bim.length+length_bim.height)/2],
               'center': [0,-(width_bim.length+length_bim.width)/2,(height_bim.length+length_bim.height)/2],
               'width':length_bim.web_thickness,'height':length_bim.height-2*length_bim.flange_thickness},
     'data3': {'p':'11', 
               'center1': [-length_bim.length/2,-(width_bim.length+length_bim.width)/2,(height_bim.length+2*length_bim.height-length_bim.flange_thickness)/2],
               'center2': [length_bim.length/2,-(width_bim.length+length_bim.width)/2,(height_bim.length+2*length_bim.height-length_bim.flange_thickness)/2],
               'center': [0,-(width_bim.length+length_bim.width)/2,(height_bim.length+2*length_bim.height-length_bim.flange_thickness)/2],
               'width':length_bim.width,'height':length_bim.flange_thickness}
     }, {'beam': 12 ,'type': 'H','length_direction':'y','width_direction':'x','height_direction':'z','length':width_bim.length,
     'data1': {'p':'12',
                'center1': [-(length_bim.length+width_bim.width)/2,width_bim.length/2,(height_bim.length+width_bim.flange_thickness)/2], 
                'center2': [-(length_bim.length+width_bim.width)/2,-width_bim.length/2,(height_bim.length+width_bim.flange_thickness)/2],
                'center':[-(length_bim.length+width_bim.width)/2,0,(height_bim.length+width_bim.flange_thickness)/2],
                'width':width_bim.width,'height':width_bim.flange_thickness},
     'data2': {'p':'12',
               'center1': [-(length_bim.length+width_bim.width)/2,width_bim.length/2,(height_bim.length+width_bim.height)/2],
               'center2': [-(length_bim.length+width_bim.width)/2,-width_bim.length/2,(height_bim.length+width_bim.height)/2],
               'center': [-(length_bim.length+width_bim.width)/2,0,(height_bim.length+width_bim.height)/2],
               'width':width_bim.web_thickness,'height':width_bim.height-2*width_bim.flange_thickness},
     'data3': {'p':'12',
                'center1': [-(length_bim.length+width_bim.width)/2,width_bim.length/2,(height_bim.length+2*width_bim.height-width_bim.flange_thickness)/2], 
                'center2': [-(length_bim.length+width_bim.width)/2,-width_bim.length/2,(height_bim.length+2*width_bim.height-width_bim.flange_thickness)/2],
                'center':[-(length_bim.length+width_bim.width)/2,0,(height_bim.length+2*width_bim.height-width_bim.flange_thickness)/2],
                'width':width_bim.width,'height':width_bim.flange_thickness}
     }
    ]

        json_file_name = 'group.json'

# 获取当前工作目录
        current_working_directory = os.getcwd()
        json_file_path = os.path.join(current_working_directory, json_file_name)

# 打开文件进行写入
        try:
            with open(json_file_path, 'w', encoding='utf-8') as f:
        # 将列表写入文件，每个列表元素都是一组数据
                json.dump(data, f, ensure_ascii=False, indent=4)
            print(f"File '{json_file_name}' successfully written to directory '{current_working_directory}'.")
        except IOError as e:
            print(f"An I/O error occurred: {e.strerror}")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")